#连接数据库
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///mydb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456